name: Docker image CI for ghcr.io

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Extract version from composer.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .version composer.json -r'
      
      - name: Show my version
        run: 'echo "version ${{ steps.version.outputs.value }}"'
